# This is a very basic config for the `docs` branch designed to prevent a build error
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "Hello world"
