name: Tag and deploy to staging

on:
  workflow_dispatch:
    inputs:
      releaseCandidateVersion:
        description: "Numéro de la version de base (ex RC-xxx, v191.1.1)"
        required: true
        type: string
      releaseVersion:
        description: "Nom de la release (ex: 199.0.0)"
        required: true
        type: string

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RC
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.releaseCandidateVersion }}
      - name: Author
        run: |
          git config --global user.email "github-actions-bot@passculture.app"
          git config --global user.name "${{ github.actor }}"
      - name: Tag Release
        run: |
          ./pc -t ${{ github.event.inputs.releaseVersion }} tag

  deploy-to-staging:
    needs: tag-version
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
        with:
          ref: v${{ github.event.inputs.releaseVersion }}
      - name: Deploy Release to staging
        run: |
          ./pc -e staging -t ${{ github.event.inputs.releaseVersion }} deploy

  deploy-to-production:
    needs: tag-version
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout Release
        uses: actions/checkout@v3
        with:
          ref: v${{ github.event.inputs.releaseVersion }}
      - name: Deploy Release to production
        run: |
          echo "would have deployed to production but do it manually this time"
