name: Test main
run-name: Test main${{ github.ref == 'refs/heads/master' && ' and deploy to testing' || '' }}
on:
  push:

concurrency:
  # cancel previous workflow of the same branch except on master
  group: ${{ github.ref == 'refs/heads/master' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:

  build-api:
    name: Build api docker image on master branch
    uses: ./.github/workflows/build-and-push-docker-images.yml
    with:
      tag: ${{ github.sha }}
      console: true
    secrets: inherit

