name: Test main
run-name: Test main${{ github.ref == 'refs/heads/master' && ' and deploy to testing' || '' }}
on:
  push:

concurrency:
  # cancel previous workflow of the same branch except on master
  group: ${{ github.ref == 'refs/heads/master' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  check-adage-folder-changes:
    name: Check adage folder changes
    uses: pass-culture/troubleshoot-changed-file/.github/workflows/check-folder-changes.yml@master
    with:
      folder: adage-front

