name: Test main
run-name: Test main${{ github.ref == 'refs/heads/master' && ' and deploy to testing' || '' }}
on:
  push:

jobs:
  check-adage-folder-changes:
    name: Check adage folder changes
    uses: ./.github/workflows/check-folder-changes.yml
    with:
      folder: adage-front

  check-api-folder-changes:
    name: Check api folder changes
    uses: ./.github/workflows/check-folder-changes.yml
    with:
      folder: api

  check-backoffice-folder-changes:
    name: Check backoffice folder changes
    uses: ./.github/workflows/check-folder-changes.yml
    with:
      folder: backoffice

  check-pro-folder-changes:
    name: Check pro folder changes
    uses: ./.github/workflows/check-folder-changes.yml
    with:
      folder: pro

  debug:
    needs:
      - check-pro-folder-changes
      - check-api-folder-changes
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "${{ needs.check-api-folder-changes.outputs.folder_changed == 'true' }}\n"
          echo "${{ needs.check-pro-folder-changes.outputs.folder_changed == 'true' }}\n"

